<p style="text-align:center">
    <a href="https://skills.network" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo">
    </a>
</p>

# **SpaceX  Falcon 9 first stage Landing Prediction**

# Lab 1: Collecting the data

Estimated time needed: **45** minutes

In this capstone, we will predict if the Falcon 9 first stage will land successfully. SpaceX advertises Falcon 9 rocket launches on its website with a cost of 62 million dollars; other providers cost upward of 165 million dollars each, much of the savings is because SpaceX can reuse the first stage. Therefore if we can determine if the first stage will land, we can determine the cost of a launch. This information can be used if an alternate company wants to bid against SpaceX for a rocket launch. In this lab, you will collect and make sure the data is in the correct format from an API. The following is an example of a successful and launch.

![](https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DS0701EN-SkillsNetwork/lab_v2/images/landing_1.gif)

Several examples of an unsuccessful landing are shown here:

![](https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DS0701EN-SkillsNetwork/lab_v2/images/crash.gif)

Most unsuccessful landings are planned. Space X performs a controlled landing in the oceans.

## Objectives

In this lab, you will make a get request to the SpaceX API. You will also do some basic data wrangling and formating. 

- Request to the SpaceX API
- Clean the requested data

----

## Import Libraries and Define Auxiliary Functions

We will import the following libraries into the lab

In [2]:
# Requests allows us to make HTTP requests which we will use to get data from an API
import requests
# Pandas is a software library written for the Python programming language for data manipulation and analysis.
import pandas as pd
# NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays
import numpy as np
# Datetime is a library that allows us to represent dates
import datetime

# Setting this option will print all collumns of a dataframe
pd.set_option('display.max_columns', None)
# Setting this option will print all of the data in a feature
pd.set_option('display.max_colwidth', None)

Below we will define a series of helper functions that will help us use the API to extract information using identification numbers in the launch data.

From the <code>rocket</code> column we would like to learn the booster name.

In [3]:
# Takes the dataset and uses the rocket column to call the API and append the data to the list

def getBoosterVersion(data):
    for x in data['rocket']:
        if x:
            response = requests.get("https://gateway.pipeworx.io/spacex/v4/rockets/"+str(x)).json()
            if 'name' in response:
                BoosterVersion.append(response['name'])
            else:
                # Accurately identify Falcon 1 vs Falcon 9 by rocket ID
                if x == '5e9d0d95eda69955f709d1eb':
                    BoosterVersion.append('Falcon 1')
                else:
                    BoosterVersion.append('Falcon 9')

# Important note: the SpaceX API was taken down in June 2026. 
# I replaced the API link to https://gateway.pipeworx.io/spacex/v4/ which is a community-based replacement.

From the <code>launchpad</code> we would like to know the name of the launch site being used, the logitude, and the latitude.

In [4]:
# Takes the dataset and uses the launchpad column to call the API and append the data to the list
def getLaunchSite(data):
    for x in data['launchpad']:
       if x:
         response = requests.get("https://gateway.pipeworx.io/spacex/v4/launchpads/"+str(x)).json()
         Longitude.append(response.get('longitude', None))
         Latitude.append(response.get('latitude', None))
         LaunchSite.append(response.get('name', None))

# Important note: the SpaceX API was taken down in June 2026. 
# I replaced the API link to https://gateway.pipeworx.io/spacex/v4/ which is a community-based replacement.

From the <code>payload</code> we would like to learn the mass of the payload and the orbit that it is going to.

In [5]:
# Takes the dataset and uses the payloads column to call the API and append the data to the lists
def getPayloadData(data):
    for load in data['payloads']:
       if load:
        response = requests.get("https://gateway.pipeworx.io/spacex/v4/payloads/"+load).json()
        PayloadMass.append(response.get('mass_kg', None))
        Orbit.append(response.get('orbit', None))

# Important note: the SpaceX API was taken down in June 2026. 
# I replaced the API link to https://gateway.pipeworx.io/spacex/v4/ which is a community-based replacement.

From <code>cores</code> we would like to learn the outcome of the landing, the type of the landing, number of flights with that core, whether gridfins were used, wheter the core is reused, wheter legs were used, the landing pad used, the block of the core which is a number used to seperate version of cores, the number of times this specific core has been reused, and the serial of the core.

In [6]:
# Takes the dataset and uses the cores column to call the API and append the data to the lists
def getCoreData(data):
    for core in data['cores']:
            if core['core'] != None:
                response = requests.get("https://gateway.pipeworx.io/spacex/v4/cores/"+core['core']).json()
                Block.append(response.get('block', None))
                ReusedCount.append(response.get('reuse_count', None))
                Serial.append(response.get('serial', None))
            else:
                Block.append(None)
                ReusedCount.append(None)
                Serial.append(None)
            Outcome.append(str(core['landing_success'])+' '+str(core['landing_type']))
            Flights.append(core['flight'])
            GridFins.append(core['gridfins'])
            Reused.append(core['reused'])
            Legs.append(core['legs'])
            LandingPad.append(core['landpad'])

# Important note: the SpaceX API was taken down in June 2026. 
# I replaced the API link to https://gateway.pipeworx.io/spacex/v4/ which is a community-based replacement.

Now let's start requesting rocket launch data from SpaceX API with the following URL:

In [7]:
spacex_url="https://gateway.pipeworx.io/spacex/v4/launches/past"

# Important note: the SpaceX API was taken down in June 2026. 
# I replaced the API link to https://gateway.pipeworx.io/spacex/v4/ which is a community-based replacement.

In [8]:
response = requests.get(spacex_url)

Check the content of the response

In [9]:
print(response.content)

b'[\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 17-50",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-08-19T04:01:07Z"\n },\n {\n  "name": "Falcon 9 Block 5 | USSF-366",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-08-16T01:50:45Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Globalstar 2-R Mission 1 (x 8)",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-08-16T01:12:14Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 17-49",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-08-12T04:46:47Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 10-19",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-08-11T15:58:26Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 17-38",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-08-08T16:35:02Z"\n },\n {\n  "name": "Falcon 9 Block 5 | BlueBird 11-13 (Block 2 #6-8)",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-08-05T07:49:00Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 17-53",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-08-04T17:05:03Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 17-52",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-08-01T03:08:43Z"\n },\n {\n  "name": "Falcon 9 Block 5 | NROL-95",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-07-30T07:10:19Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 17-51",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-07-25T15:51:55Z"\n },\n {\n  "name": "Starship | Flight 13",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-07-24T22:51:00Z"\n },\n {\n  "name": "Falcon 9 Block 5 | MRV-1",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-07-21T21:15:00Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 17-39",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-07-21T14:49:34Z"\n },\n {\n  "name": "Falcon 9 Block 5 | SDA Tranche 1 Transport Layer E",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-07-16T20:32:36Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 10-45",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-07-14T09:10:12Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 15-14",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-07-14T01:28:17Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 17-48",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-07-11T03:01:57Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 10-42",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-07-09T09:25:43Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Transporter 17 (Dedicated SSO Rideshare)",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-07-07T07:12:00Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 10-50",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-07-05T10:50:00Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 17-46",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-07-02T02:58:19Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Sirius SXM-11",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-06-29T02:25:00Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 17-40",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-06-28T16:09:18Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 17-45",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-06-25T03:30:38Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Project Starfall Demonstration Mission",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-06-23T10:53:00Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 17-28",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-06-21T16:39:06Z"\n },\n {\n  "name": "Falcon 9 Block 5 | NROL-179",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-06-19T08:50:45Z"\n },\n {\n  "name": "Falcon 9 Block 5 | BlueBird 8-10 (Block 2 #3-5)",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-06-17T06:39:00Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 17-54",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-06-15T15:34:35Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 10-54",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-06-12T12:37:00Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 17-44",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-06-11T15:05:59Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 10-35",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-06-08T10:13:50Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 17-43",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-06-07T04:24:45Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 10-43",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-06-04T10:26:30Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 17-47",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-06-03T15:40:39Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 17-41",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-05-30T15:25:10Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 10-53",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-05-29T12:57:15Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 17-37",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-05-26T14:50:34Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 10-47",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-05-25T11:48:04Z"\n },\n {\n  "name": "Starship | Flight 12",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-05-22T22:30:24Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 10-31",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-05-21T10:04:20Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 17-42",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-05-20T02:46:19Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Dragon CRS-2 SpX-34",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-05-15T22:05:41Z"\n },\n {\n  "name": "Falcon 9 Block 5 | NROL-172",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-05-12T02:13:50Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 17-29",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-05-06T03:59:19Z"\n },\n {\n  "name": "Falcon 9 Block 5 | CAS500-2 & Others",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-05-03T07:00:00Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 10-38",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-05-01T18:06:10Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 17-36",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-04-30T02:42:49Z"\n },\n {\n  "name": "Falcon Heavy | ViaSat-3 F3 (ViaSat-3 Asia-Pacific)",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-04-29T14:13:00Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 17-16",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-04-26T14:37:09Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 17-14",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-04-23T03:23:09Z"\n },\n {\n  "name": "Falcon 9 Block 5 | GPS III SV10",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-04-21T06:53:25Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 17-22",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-04-19T16:03:09Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 17-27",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-04-15T04:29:49Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 10-24",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-04-14T09:33:10Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Cygnus CRS-2 NG-24 (S.S. Steven R. Nagel)",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-04-11T11:41:21Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 17-21",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-04-11T05:04:19Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 17-35",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-04-07T02:50:39Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 10-58",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-04-02T11:55:10Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 10-44",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-03-30T21:15:00Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Transporter 16 (Dedicated SSO Rideshare)",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-03-30T11:02:00Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 17-17",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-03-26T23:03:19Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 10-62",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-03-22T14:47:00Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 17-15",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-03-20T21:51:49Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 10-33",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-03-19T14:20:10Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 10-46",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-03-17T13:27:34Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 17-24",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-03-17T05:19:09Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 10-48",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-03-14T12:37:10Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 17-31",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-03-13T14:57:59Z"\n },\n {\n  "name": "Falcon 9 Block 5 | EchoStar 25",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-03-10T04:19:00Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 17-18",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-03-08T11:00:19Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 10-40",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-03-04T10:52:20Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 10-41",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-03-02T02:56:40Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 17-23",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-03-01T10:10:39Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 6-108",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-02-27T12:16:10Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 17-26",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-02-25T14:17:49Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 6-110",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-02-24T23:04:10Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 6-104",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-02-22T03:47:10Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 17-25",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-02-21T09:04:19Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 10-36",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-02-20T01:41:40Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 6-103",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-02-16T07:59:40Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 17-13",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-02-15T01:59:59Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Crew-12",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-02-13T10:15:56Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 17-34",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-02-11T17:11:29Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 17-33",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-02-07T20:58:09Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 17-32",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-02-02T15:47:11Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 6-101",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-01-30T07:22:00Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 17-19",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-01-29T17:53:20Z"\n },\n {\n  "name": "Falcon 9 Block 5 | GPS III SV09",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-01-28T04:53:16Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 17-20",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-01-25T17:30:39Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 17-30",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-01-22T05:47:29Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 6-100",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-01-18T23:31:40Z"\n },\n {\n  "name": "Falcon 9 Block 5 | NROL-105",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-01-17T04:39:51Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 6-98",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-01-14T18:08:20Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 6-97",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-01-12T21:08:20Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Pandora / Twilight rideshare mission",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-01-11T13:44:50Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 6-96",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-01-09T21:41:00Z"\n },\n {\n  "name": "Falcon 9 Block 5 | Starlink Group 6-88",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-01-04T06:48:10Z"\n },\n {\n  "name": "Falcon 9 Block 5 | CSG-3",\n  "status": "Launch Successful",\n  "success": true,\n  "date_utc": "2026-01-03T02:09:16Z"\n }\n]'

You should see the response contains massive information about SpaceX launches. Next, let's try to discover some more relevant information for this project.

### Task 1: Request and parse the SpaceX launch data using the GET request

To make the requested JSON results more consistent, we will use the following static response object for this project:

In [10]:
static_json_url='https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/datasets/API_call_spacex_api.json'

We should see that the request was successfull with the 200 status response code

In [11]:
response=requests.get(static_json_url)

In [12]:
response.status_code

200

Now we decode the response content as a Json using <code>.json()</code> and turn it into a Pandas dataframe using <code>.json_normalize()</code>

In [13]:
# Use json_normalize meethod to convert the json result into a dataframe
data = pd.json_normalize(response.json())

Using the dataframe <code>data</code> print the first 5 rows

In [14]:
# Get the head of the dataframe
data.head()

,static_fire_date_utc,static_fire_date_unix,tbd,net,window,rocket,success,details,crew,ships,capsules,payloads,launchpad,auto_update,failures,flight_number,name,date_utc,date_unix,date_local,date_precision,upcoming,cores,id,fairings.reused,fairings.recovery_attempt,fairings.recovered,fairings.ships,links.patch.small,links.patch.large,links.reddit.campaign,links.reddit.launch,links.reddit.media,links.reddit.recovery,links.flickr.small,links.flickr.original,links.presskit,links.webcast,links.youtube_id,links.article,links.wikipedia,fairings
0,2006-03-17T00:00:00.000Z,1.142554e+09,False,False,0.0,5e9d0d95eda69955f709d1eb,False,Engine failure at 33 seconds and loss of vehicle,[],[],[],[5eb0e4b5b6c3bb0006eeb1e1],5e9e4502f5090995de566f86,True,"[{'time': 33, 'altitude': None, 'reason': 'merlin engine failure'}]",1,FalconSat,2006-03-24T22:30:00.000Z,1143239400,2006-03-25T10:30:00+12:00,hour,False,"[{'core': '5e9e289df35918033d3b2623', 'flight': 1, 'gridfins': False, 'legs': False, 'reused': False, 'landing_attempt': False, 'landing_success': None, 'landing_type': None, 'landpad': None}]",5eb87cd9ffd86e000604b32a,False,False,False,[],https://images2.imgbox.com/3c/0e/T8iJcSN3_o.png,https://images2.imgbox.com/40/e3/GypSkayF_o.png,NaN,NaN,NaN,NaN,[],[],NaN,https://www.youtube.com/watch?v=0a_00nJ_Y88,0a_00nJ_Y88,https://www.space.com/2196-spacex-inaugural-falcon-1-rocket-lost-launch.html,https://en.wikipedia.org/wiki/DemoSat,NaN
1,NaN,NaN,False,False,0.0,5e9d0d95eda69955f709d1eb,False,"Successful first stage burn and transition to second stage, maximum altitude 289 km, Premature engine shutdown at T+7 min 30 s, Failed to reach orbit, Failed to recover first stage",[],[],[],[5eb0e4b6b6c3bb0006eeb1e2],5e9e4502f5090995de566f86,True,"[{'time': 301, 'altitude': 289, 'reason': 'harmonic oscillation leading to premature engine shutdown'}]",2,DemoSat,2007-03-21T01:10:00.000Z,1174439400,2007-03-21T13:10:00+12:00,hour,False,"[{'core': '5e9e289ef35918416a3b2624', 'flight': 1, 'gridfins': False, 'legs': False, 'reused': False, 'landing_attempt': False, 'landing_success': None, 'landing_type': None, 'landpad': None}]",5eb87cdaffd86e000604b32b,False,False,False,[],https://images2.imgbox.com/4f/e3/I0lkuJ2e_o.png,https://images2.imgbox.com/be/e7/iNqsqVYM_o.png,NaN,NaN,NaN,NaN,[],[],NaN,https://www.youtube.com/watch?v=Lk4zQ2wP-Nc,Lk4zQ2wP-Nc,https://www.space.com/3590-spacex-falcon-1-rocket-fails-reach-orbit.html,https://en.wikipedia.org/wiki/DemoSat,NaN
2,NaN,NaN,False,False,0.0,5e9d0d95eda69955f709d1eb,False,Residual stage 1 thrust led to collision between stage 1 and stage 2,[],[],[],"[5eb0e4b6b6c3bb0006eeb1e3, 5eb0e4b6b6c3bb0006eeb1e4]",5e9e4502f5090995de566f86,True,"[{'time': 140, 'altitude': 35, 'reason': 'residual stage-1 thrust led to collision between stage 1 and stage 2'}]",3,Trailblazer,2008-08-03T03:34:00.000Z,1217734440,2008-08-03T15:34:00+12:00,hour,False,"[{'core': '5e9e289ef3591814873b2625', 'flight': 1, 'gridfins': False, 'legs': False, 'reused': False, 'landing_attempt': False, 'landing_success': None, 'landing_type': None, 'landpad': None}]",5eb87cdbffd86e000604b32c,False,False,False,[],https://images2.imgbox.com/3d/86/cnu0pan8_o.png,https://images2.imgbox.com/4b/bd/d8UxLh4q_o.png,NaN,NaN,NaN,NaN,[],[],NaN,https://www.youtube.com/watch?v=v0w9p3U8860,v0w9p3U8860,http://www.spacex.com/news/2013/02/11/falcon-1-flight-3-mission-summary,https://en.wikipedia.org/wiki/Trailblazer_(satellite),NaN
3,2008-09-20T00:00:00.000Z,1.221869e+09,False,False,0.0,5e9d0d95eda69955f709d1eb,True,"Ratsat was carried to orbit on the first successful orbital launch of any privately funded and developed, liquid-propelled carrier rocket, the SpaceX Falcon 1",[],[],[],[5eb0e4b7b6c3bb0006eeb1e5],5e9e4502f5090995de566f86,True,[],4,RatSat,2008-09-28T23:15:00.000Z,1222643700,2008-09-28T11:15:00+12:00,hour,False,"[{'core': '5e9e289ef3591855dc3b2626', 'flight': 1, 'gridfins': False, 'legs': False, 'reused': False, 'landing_attempt': False, 'landing_success': None, 'landing_type': None, 'landpad': None}]",5eb87cdbffd86e000604b32d,False,False,False,[],https://images2.imgbox.com/e9/c9/T8CfiSYb_o.png,https://images2.imgbox.com/e0/a7/FNjvKlXW_o.png,NaN,NaN,NaN,NaN,[],[],NaN,https://www.youtube.com/watch?v=dLQ2tZEH6G0,dLQ2tZEH6G0,https://en.wikipedia.org/wiki/Ratsat,https://en.wikipedia.org/wiki/Ratsat,NaN
4,NaN,NaN,False,False,0.0,5e9d0d95eda69955f709d1eb,True,NaN,[],[],[],[5eb0e4b7b6c3bb0006eeb1e6],5e9e4502f5090995de566f86,True,[],5,RazakSat,2009-07-13T03:35:00.000Z,1247456100,2009-07-13T15:35:00+12:00,hour,False,"[{'core': '5e9e289ef359184f103b2627', 'flight': 1, 'gridfins': False, 'legs': False, 'reused': False, 'landing_attempt': False, 'landing_success': None, 'landing_type': None, 'landpad': None}]",5eb87cdcffd86e000604b32e,False,False,False,[],https://images2.imgbox.com/a7/ba/NBZSw3Ho_o.png,https://images2.imgbox.com/8d/fc/0qdZMWWx_o.png,NaN,NaN,NaN,NaN,[],[],http://www.spacex.com/press/2012/12/19/spacexs-falcon-1-successfully-delivers-razaksat-satellite-orbit,https://www.youtube.com/watch?v=yTaIDooc8Og,yTaIDooc8Og,http://www.spacex.com/news/2013/02/12/falcon-1-flight-5,https://en.wikipedia.org/wiki/RazakSAT,NaN

You will notice that a lot of the data are IDs. For example the rocket column has no information about the rocket just an identification number.

We will now use the API again to get information about the launches using the IDs given for each launch. Specifically we will be using columns <code>rocket</code>, <code>payloads</code>, <code>launchpad</code>, and <code>cores</code>.

In [15]:
# Lets take a subset of our dataframe keeping only the features we want and the flight number, and date_utc.
data = data[['rocket', 'payloads', 'launchpad', 'cores', 'flight_number', 'date_utc']]

# We will remove rows with multiple cores because those are falcon rockets with 2 extra rocket boosters and rows that have multiple payloads in a single rocket.
data = data[data['cores'].map(len)==1]
data = data[data['payloads'].map(len)==1]

# Since payloads and cores are lists of size 1 we will also extract the single value in the list and replace the feature.
data['cores'] = data['cores'].map(lambda x : x[0])
data['payloads'] = data['payloads'].map(lambda x : x[0])

# We also want to convert the date_utc to a datetime datatype and then extracting the date leaving the time
data['date'] = pd.to_datetime(data['date_utc']).dt.date

# Using the date we will restrict the dates of the launches
data = data[data['date'] <= datetime.date(2020, 11, 13)]

* From the <code>rocket</code> we would like to learn the booster name

* From the <code>payload</code> we would like to learn the mass of the payload and the orbit that it is going to

* From the <code>launchpad</code> we would like to know the name of the launch site being used, the longitude, and the latitude.

* **From <code>cores</code> we would like to learn the outcome of the landing, the type of the landing, number of flights with that core, whether gridfins were used, whether the core is reused, whether legs were used, the landing pad used, the block of the core which is a number used to seperate version of cores, the number of times this specific core has been reused, and the serial of the core.**

The data from these requests will be stored in lists and will be used to create a new dataframe.

In [16]:
#Global variables 
BoosterVersion = []
PayloadMass = []
Orbit = []
LaunchSite = []
Outcome = []
Flights = []
GridFins = []
Reused = []
Legs = []
LandingPad = []
Block = []
ReusedCount = []
Serial = []
Longitude = []
Latitude = []

These functions will apply the outputs globally to the above variables. Let's take a looks at <code>BoosterVersion</code> variable. Before we apply  <code>getBoosterVersion</code> the list is empty:

In [17]:
BoosterVersion

[]

Now, let's apply <code> getBoosterVersion</code> function method to get the booster version

In [18]:
# Call getBoosterVersion
getBoosterVersion(data)

the list has now been updated

In [19]:
BoosterVersion[0:5]

['Falcon 1', 'Falcon 1', 'Falcon 1', 'Falcon 1', 'Falcon 9']

we can apply the rest of the  functions here:

In [20]:
# Call getLaunchSite
getLaunchSite(data)

In [21]:
# Call getPayloadData
getPayloadData(data)

In [22]:
# Call getCoreData
getCoreData(data)

Finally lets construct our dataset using the data we have obtained. We we combine the columns into a dictionary.

In [23]:
launch_dict = {'FlightNumber': list(data['flight_number']),
'Date': list(data['date']),
'BoosterVersion':BoosterVersion,
'PayloadMass':PayloadMass,
'Orbit':Orbit,
'LaunchSite':LaunchSite,
'Outcome':Outcome,
'Flights':Flights,
'GridFins':GridFins,
'Reused':Reused,
'Legs':Legs,
'LandingPad':LandingPad,
'Block':Block,
'ReusedCount':ReusedCount,
'Serial':Serial,
'Longitude': Longitude,
'Latitude': Latitude}

Then, we need to create a Pandas data frame from the dictionary launch_dict.

In [24]:
# Create a data from launch_dict
data = pd.DataFrame(launch_dict)

Show the summary of the dataframe

In [25]:
# Show the head of the dataframe
data.head()

,FlightNumber,Date,BoosterVersion,PayloadMass,Orbit,LaunchSite,Outcome,Flights,GridFins,Reused,Legs,LandingPad,Block,ReusedCount,Serial,Longitude,Latitude
0,1,2006-03-24,Falcon 1,None,None,None,None None,1,False,False,False,NaN,None,None,None,None,None
1,2,2007-03-21,Falcon 1,None,None,None,None None,1,False,False,False,NaN,None,None,None,None,None
2,4,2008-09-28,Falcon 1,None,None,None,None None,1,False,False,False,NaN,None,None,None,None,None
3,5,2009-07-13,Falcon 1,None,None,None,None None,1,False,False,False,NaN,None,None,None,None,None
4,6,2010-06-04,Falcon 9,None,None,None,None None,1,False,False,False,NaN,None,None,None,None,None

### Task 2: Filter the dataframe to only include `Falcon 9` launches

Finally we will remove the Falcon 1 launches keeping only the Falcon 9 launches. Filter the data dataframe using the <code>BoosterVersion</code> column to only keep the Falcon 9 launches. Save the filtered data to a new dataframe called <code>data_falcon9</code>.

In [26]:
# Hint data['BoosterVersion']!='Falcon 1'
data_falcon9 = data[data['BoosterVersion'] != 'Falcon 1'].copy()

Now that we have removed some values we should reset the FlgihtNumber column

In [27]:
data_falcon9.loc[:,'FlightNumber'] = list(range(1, data_falcon9.shape[0]+1))
data_falcon9

,FlightNumber,Date,BoosterVersion,PayloadMass,Orbit,LaunchSite,Outcome,Flights,GridFins,Reused,Legs,LandingPad,Block,ReusedCount,Serial,Longitude,Latitude
4,1,2010-06-04,Falcon 9,None,None,None,None None,1,False,False,False,NaN,None,None,None,None,None
5,2,2012-05-22,Falcon 9,None,None,None,None None,1,False,False,False,NaN,None,None,None,None,None
6,3,2013-03-01,Falcon 9,None,None,None,None None,1,False,False,False,NaN,None,None,None,None,None
7,4,2013-09-29,Falcon 9,None,None,None,False Ocean,1,False,False,False,NaN,None,None,None,None,None
8,5,2013-12-03,Falcon 9,None,None,None,None None,1,False,False,False,NaN,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89,86,2020-09-03,Falcon 9,None,None,None,True ASDS,2,True,True,True,5e9e3032383ecb6bb234e7ca,None,None,None,None,None
90,87,2020-10-06,Falcon 9,None,None,None,True ASDS,3,True,True,True,5e9e3032383ecb6bb234e7ca,None,None,None,None,None
91,88,2020-10-18,Falcon 9,None,None,None,True ASDS,6,True,True,True,5e9e3032383ecb6bb234e7ca,None,None,None,None,None
92,89,2020-10-24,Falcon 9,None,None,None,True ASDS,3,True,True,True,5e9e3033383ecbb9e534e7cc,None,None,None,None,None
93,90,2020-11-05,Falcon 9,None,None,None,True ASDS,1,True,False,True,5e9e3032383ecb6bb234e7ca,None,None,None,None,None

## Data Wrangling

We can see below that some of the rows are missing values in our dataset.

In [28]:
data_falcon9.isnull().sum()

FlightNumber       0
Date               0
BoosterVersion     0
PayloadMass       90
Orbit             90
LaunchSite        90
Outcome            0
Flights            0
GridFins           0
Reused             0
Legs               0
LandingPad        26
Block             90
ReusedCount       90
Serial            90
Longitude         90
Latitude          90
dtype: int64

Before we can continue we must deal with these missing values. The <code>LandingPad</code> column will retain None values to represent when landing pads were not used.

### Task 3: Dealing with Missing Values

Calculate below the mean for the <code>PayloadMass</code> using the <code>.mean()</code>. Then use the mean and the <code>.replace()</code> function to replace `np.nan` values in the data with the mean you calculated.

In [29]:
# Calculate the mean value of PayloadMass column
mean_payload = data_falcon9['PayloadMass'].mean()

# Replace the np.nan values with its mean value
data_falcon9['PayloadMass'] = data_falcon9['PayloadMass'].replace(np.nan, mean_payload)

You should see the number of missing values of the <code>PayLoadMass</code> change to zero.

Now we should have no missing values in our dataset except for in <code>LandingPad</code>.

We can now export it to a <b>CSV</b> for the next section,but to make the answers consistent, in the next lab we will provide data in a pre-selected date range.

<code>data_falcon9.to_csv('dataset_part_1.csv', index=False)</code>

In [30]:
# Coursera quiz questions

In [31]:
# Question 1
temp_data = pd.json_normalize(response.json())
first_row_date = temp_data.loc[0, 'static_fire_date_utc']
year = str(first_row_date).split('-')[0]

print(f"Question 1: {year}")

Question 1: 2006

In [32]:
# Question 2
falcon9_launch_count = data_falcon9.shape[0]

print(f"Question 2: {falcon9_launch_count}")

Question 2: 90

In [33]:
# Question 3
missing_landingpads = data_falcon9['LandingPad'].isnull().sum()

print(f"Question 3: {missing_landingpads}")

Question 3: 26

## Authors

<a href="https://www.linkedin.com/in/joseph-s-50398b136/">Joseph Santarcangelo</a> has a PhD in Electrical Engineering, his research focused on using machine learning, signal processing, and computer vision to determine how videos impact human cognition. Joseph has been working for IBM since he completed his PhD.

<!--## Change Log
-->

<!--

|Date (YYYY-MM-DD)|Version|Changed By|Change Description|
|-|-|-|-|
|2020-09-20|1.1|Joseph|get result each time you run|
|2020-09-20|1.1|Azim |Created Part 1 Lab using SpaceX API|
|2020-09-20|1.0|Joseph |Modified Multiple Areas|
-->

Copyright ©IBM Corporation. All rights reserved.